### ISSUE TITLE
Spike 1 usertest 4-12 op mobiel leden pagina

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#131]
is de animatie duidelijk?

is de animatie prettig of is er teveel interactie?

is het overzichtelijk?

heb je feedback van hoe ik dit zou kunnen verbeteren

**Comment by yujing-student** [comment]
de usertest op mobiel

hij begon bij de cards en scrolde steeds door tot het einde van alle cardds

**Comment by lemuelmgsn** [comment]
## Screenshots waar ik feedback op heb:

### Feedback: 
Toen ik op de pagina belandde zag ik dat het een pagina was waar je bureaus kan opzoeken. Omdat eronder veel witruimte is dacht ik dat er niks anders te vinden was op de pagina totdat ik een beetje naar beneden ging scrollen. En er opeens een pop-in animatie was.

Ik heb als tip om hier of de animatie wat eerder te laten beginnen of dat je een kleine teaser kan geven dat er een animatie is.

![image](https://github.com/user-attachments/assets/4f7ff297-d11c-477c-b593-ad509faf13ef)

![image](https://github.com/user-attachments/assets/00c24b98-1d14-48ac-ac05-0a6f92a00338)

![image](https://github.com/user-attachments/assets/ab3ea06b-3103-49e8-8761-0b9c48dc3311)

Ook onder deze artikel is veel witruimte waardoor ik dacht dat dit de laatste artikel was, maar als je weer verder scrollt komen er nog meer pop-ins

![image](https://github.com/user-attachments/assets/55fd395a-8dad-48ca-9124-6dc0b88c2fc8)

**Comment by yujing-student** [comment]
![image](https://github.com/user-attachments/assets/798d7906-9157-4e8a-a1af-9e00f83309e8)


dit heb ik opgelost door een slide up erin te doen in plaats van links zodat je ook direct het begin ziet van de volgende card


https://github.com/user-attachments/assets/50922381-cea6-4866-911c-4b4ee4fc37ca

**Comment by lemuelmgsn** [comment]
Top! Je hebt er een mooie en simpele animatie van gemaakt die goed bij de stijl van jullie project past. Het is overzichtelijk en het is er zit niet te veel interactie/afleiding
