### ISSUE TITLE
Spike 1 usertest 4-12 op tablet leden pagina

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#132]
is de animatie duidelijk?

is de animatie prettig of is er teveel interactie?

is het overzichtelijk?

heb je feedback van hoe ik dit zou kunnen verbeteren

**Comment by lemuelmgsn** [comment]
is de animatie duidelijk?
> Animatie is duidelijk maar niet heel ideaal

is de animatie prettig of is er teveel interactie?
> ik vind de animatie creatief! maar ik denk dat er toch iets te veel interactie is. 

is het overzichtelijk?
> Het is niet echt overzichtelijk, wanneer je in het midden van je scherm bent zie je de linker artikel niet helemaal (zie screenshots)

heb je feedback van hoe ik dit zou kunnen verbeteren
> je kan de kaartje niet volledig 360 graden draaien.

## Screenshots

![image](https://github.com/user-attachments/assets/d73434ab-4dd5-45b4-bba3-7f8a6a53748e)

**Comment by yujing-student** [comment]
<h1>oplossing</h1>

Ik heb de spin interactie weggehaald want daar twijfelde ik over en jij was mijn proefpersoon om dit te testen en de andere animatie 

nu heb ik als oplossing dat ik een image reveal heb waarin de image klein is en groter word en dat de kleur van de card wit word waardoor de card opvalt en de tekst leesbaar is 

![image](https://github.com/user-attachments/assets/3f078b19-b321-47f2-b308-0f5b1cb3f19c)



https://github.com/user-attachments/assets/a0f9beeb-08ff-4f18-915c-8f8d852a46a7

**Comment by yujing-student** [comment]
Ik heb je feedback toegepast zie de [pull request  ](https://github.com/lisagjh/voorhoede/pull/43)
