### ISSUE TITLE
Schetsen datamodel / 1ste versie

### ISSUE THREAD

**Issue by Jason2426** [fdnd-agency/voorhoede#14]
## [FigJam link](https://www.figma.com/board/e0aZBmvu0DVndl5G9jVADm/DDA-%2F-Datamodel?node-id=01&t=rgMSsJvJrAz5f5Ax-1)

> Workshop Informatie architectuur 

![Image](https://github.com/user-attachments/assets/88b207bf-2f88-4da5-bf2d-104a8d321afe)

**Comment by yujing-student** [comment]
<h1>datamodel erd</h1>


![Image](https://github.com/user-attachments/assets/4e7569ca-306f-4831-944b-806b979b33f6)


<h2>user flow</h2>

![Image](https://github.com/user-attachments/assets/af17b150-6cb3-4eee-9243-fd22efe3a9ee)


link naar de figma breakdownschets als wireflow nog niet volledig af

https://www.figma.com/design/Cg5eZyNoPgp650bzsu4bu4/ledenpagina-sprint-14-breakdownschets?node-id=0-1&m=dev&t=R51VGXfWYOKfmGwA-1

![Image](https://github.com/user-attachments/assets/73fd1437-f4aa-467e-857d-47ea38035aae)
![Image](https://github.com/user-attachments/assets/7b75a0e2-d843-4032-a912-051ccd4df9dd)

**Comment by Jason2426** [comment]
![Image](https://github.com/user-attachments/assets/0719820b-5cb8-4fba-9767-681cf660d9d4)
