### ISSUE TITLE
Custom error pagina maken

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/voorhoede#31]
anders word justus niet blij

**Comment by yujing-student** [comment]
https://github.com/ju5tu5/sveltekit-principles voorbeeld

**Comment by yujing-student** [comment]
Ik heb de errorpage getest in een andere branch feature-member-overviewpage met pagina's die niet bestaan en daar word de errorpage wel direct getoond

![image](https://github.com/user-attachments/assets/7788f7e0-0e0c-4a33-afe4-b6972e6ef6f9)

**Comment by yujing-student** [comment]
na hulp van dorien is de conclusie:

als je http://localhost:5173/members doet dan werkt de errorpage wel 

![image](https://github.com/user-attachments/assets/53cab09c-2982-4d7e-bcf5-d1f28dad6250)



het probleem ligt dus aan de navigatie van de home naar de de members page

de errorpage is goed gelukt en het probleem ligt dus aan het member component 

![image](https://github.com/user-attachments/assets/650d2e31-8fa2-4ed0-b0ef-373dd9764693)

**Comment by yujing-student** [comment]
<h1>De oplossing van de error width in de console log</h1>

dit stukje code zorgt ervoor dat als 1 de waarde null is dat de width en height auto worden en de error in de console log is ook weg

````
    height="{member.photo?.height ? parseInt(member.photo.height) : 'auto'}"
    width="{member.photo?.width ? parseInt(member.photo.width) : 'auto'}">
````

![Image](https://github.com/user-attachments/assets/33a5fc22-e2c7-4428-89bc-b16a9393012e)
