### ISSUE TITLE
NaN bij de leden op de members pagina

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/voorhoede#32]
Zoals je in onderstaande screenshot ziet, staat er bij een aantal leden `NaN`. Ik geloof dat dit het aantal werknemers bij deze agency zou moeten zijn, maar dit gaat dus niet altijd goed.

<img width="1037" alt="Scherm­afbeelding 2024-09-30 om 15 03 16" src="https://github.com/user-attachments/assets/ed7205f5-887d-4587-8d6e-ce0c820841d9">

Misschien moeten we kijken of we hier iets voor kunnen toevoegen zodat het dit niet laat zien?

**Comment by yujing-student** [comment]
Dit komt omdat bepaalde velden leeg zijn en dan is het logisch dat deze error tevoorschijn komt

![Image](https://github.com/user-attachments/assets/f984fe9c-2a3a-4af5-89ec-5ebf7ea5cbf0)

zie hier de documentatie :
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN
https://developer.mozilla.org/en-US/docs/Glossary/NaN

**Comment by yujing-student** [comment]
<h1>dit heb ik opgelost</h1>
alle velden in de database zijn ingevuld

![image](https://github.com/user-attachments/assets/a5a6ff28-4323-4ad0-bc2f-5c7e4aa4750b)
