### ISSUE TITLE
Datamodel herontwerpen

### ISSUE THREAD

**Issue by Jason2426** [fdnd-agency/voorhoede#35]
## Research

- https://segment.com/blog/data-modeling/
- https://www.future-processing.com/blog/data-modelling/

## Het ontwerp

![Image](https://github.com/user-attachments/assets/0b98efef-a4d1-46e6-8ce6-a89709b0ab0c)

**Comment by yujing-student** [comment]
aantekeningen

Notites over data model 
We hebben gekozen voor filters waarin je op provincie kan filteren dit is een drowpdown
En dit is een dropdown geworden in directus 

Bij elke tabel moet een id in directus
Bij province is er een aparte tabel zodat de sollicitant kan filteren op provincie 

We hebben gekozen voor 2 tabellen waarin de provincie een field is zodat we ook kunnen filteren en address die staat bij de agencies en niet bij de vacatures waarin 1 bedrijf dus 1 address
De provinice is nu 1 field


We vinden de filters lastig om het data model daarop in te richten
 
Expertise is een field en geen tabel omdat dit anders heel complex word 
Province is een array
