### ISSUE TITLE
Epic, User Stories, Tasks schrijven

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/voorhoede#4]
# [Geschreven userstories](https://github.com/orgs/fdnd-agency/projects/40/views/6)
> Bekijk in deze link onze geschreven userstories en epics.

**Comment by yujing-student** [comment]
<h2>user story ik wil kunnen zoeken en filteren welke leden aangesloten zijn bij Dutch Digital Design Agencie</h2>

ik wil kunnen zoeken en filteren welke leden aangesloten zijn bij Dutch Digital Design Agencies zodat ik als sollicitant weet welke bedrijven bij mij in de buurt zitten en hoe groot de bedrijven zijn

**Comment by yujing-student** [comment]
epic: de voorhoede wil een nieuwe website voor dda realiseren 

stories:
- maak een nieuwe homepagina
- maak een vacature overzichtspagina
- maak een leden overzichtspagina

de userstories:

- #12 op de homepagina

- #7 op de ledenpagina
