### ISSUE TITLE
De tekst op de members page is te wijd en heeft niet genoeg ruimte

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/voorhoede#42]
Geef de `<p>` een max width en een margin. Gebruik eventueel `text-wrap: balance`

zorg voor genoeg witruimte, de tekst niet te breed

text-wrap: balance

**Comment by yujing-student** [comment]
![image](https://github.com/user-attachments/assets/a7018903-11c3-40e8-b0e8-a16164c7e231)

dit oplossen met code van jason slots

**Comment by yujing-student** [comment]
![image](https://github.com/user-attachments/assets/dc222054-3d1e-4a70-9426-5d9e7135d4f7)

<h1>dit heb ik opgelost</h1>

zie hier de commit : https://github.com/lisagjh/voorhoede/commit/fcfa2df9e0db158704c62867257ad016a19fb2ab

**Comment by yujing-student** [comment]
Dit heb ik toegepast zie de code

https://github.com/lisagjh/voorhoede/blob/4c36a4ce9726f7782a7c10fdf7406e6918f34f61/src/routes/members/%2Bpage.svelte#L23-L39

![Image](https://github.com/user-attachments/assets/6afbcd16-2c17-4e8b-bc1a-4ce15f57ea8d)
