### ISSUE TITLE
members page: zorg dat alles de zelfde hoogte heeft

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/voorhoede#45]
Alle velden hebben nu andere hoogtes, doordat sommige meer tekst hebben dan anderen. Zorg dat alles een hoogte heeft en recht staat.

<img width="1360" alt="Scherm­afbeelding 2024-10-06 om 14 03 33" src="https://github.com/user-attachments/assets/3996b4b1-d216-43bf-8108-0d3132a1ea4e">

**Comment by yujing-student** [comment]
<h1>dit heb ik opgelost</h1>

![image](https://github.com/user-attachments/assets/a01c430d-b5fc-45ec-91c1-966cde22120f)
