### ISSUE TITLE
Members - detail: gebruik `a` ipv `button`

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/voorhoede#46]
'detail' opent een andere pagina, dus kan je hier beter `<a>` gebruiken ipv `<button>`

<img width="431" alt="Scherm­afbeelding 2024-10-06 om 14 06 43" src="https://github.com/user-attachments/assets/2ce3a5e5-3c1d-4492-96ae-6fbfcfd0e43b">

**Comment by yujing-student** [comment]
Dit heb ik toegepast zie de link:https://github.com/fdnd-agency/voorhoede/issues/49#issuecomment-2396600684
