### ISSUE TITLE
Members page - li moet heading worden

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#49]
dit moet een heading worden en geen li

![image](https://github.com/user-attachments/assets/ad6663f6-9119-4281-aeec-da7df2de0b8f)

**Comment by lisagjh** [comment]
Je zou hier iets meer kunnen kijken naar semantiek, en wat er echt nodig is. De button staat ook in zijn eiegn `<ul>` wat naar mijn idee een beetje overbodig is.

<img width="328" alt="Scherm­afbeelding 2024-10-06 om 14 12 08" src="https://github.com/user-attachments/assets/c5ff99b9-9175-4c5d-a43f-8aad945e45ff">

**Comment by yujing-student** [comment]
Dit heb ik toegepast.

```
   <h2 class="Companyname">{member.title}</h2>

```

En button is nu een <a> element.
```
    <a href="#" class="linkdetails">details</a>
```

Zie hier de permalinks.
https://github.com/lisagjh/voorhoede/blob/d2cfe86ef53044a734047a07f0f988f5fd473c01/src/lib/Member.svelte#L22

https://github.com/lisagjh/voorhoede/blob/d2cfe86ef53044a734047a07f0f988f5fd473c01/src/lib/Member.svelte#L31
